package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/jonabadie/kanclaude-go/graph/model"
	"github.com/jonabadie/kanclaude-go/internal/store"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.NewTask) (*model.Task, error) {
	return r.Store.Create(ctx, input)
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, patch model.TaskPatch) (*model.Task, error) {
	return r.Store.Update(ctx, id, patch)
}

// MoveTask is the resolver for the moveTask field.
func (r *mutationResolver) MoveTask(ctx context.Context, id string, column model.Column, order *float64) (*model.Task, error) {
	return r.Store.Move(ctx, id, column, order)
}

// AddLog is the resolver for the addLog field.
func (r *mutationResolver) AddLog(ctx context.Context, taskID string, who model.Author, text string) (*model.Task, error) {
	return r.Store.AddLog(ctx, taskID, who, text)
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	return r.Store.Delete(ctx, id)
}

// Board is the resolver for the board field.
func (r *queryResolver) Board(ctx context.Context, column *model.Column) ([]*model.Task, error) {
	return r.Store.List(ctx, column)
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	task, err := r.Store.Get(ctx, id)
	if errors.Is(err, store.ErrNotFound) {
		return nil, nil
	}
	return task, err
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
