// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type LogEntry struct {
	Who  Author    `json:"who"`
	Text string    `json:"text"`
	At   time.Time `json:"at"`
}

type Mutation struct {
}

type NewTask struct {
	Title    string    `json:"title"`
	Desc     *string   `json:"desc,omitempty"`
	Project  *string   `json:"project,omitempty"`
	Priority *Priority `json:"priority,omitempty"`
}

type Query struct {
}

type Task struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Desc  string `json:"desc"`
	// Slash-separated path (Games/Tetris/Levels) — hierarchy is implicit.
	Project  string   `json:"project"`
	Priority Priority `json:"priority"`
	// Sort key within a priority band; lower comes first.
	Order     float64     `json:"order"`
	Column    Column      `json:"column"`
	CreatedAt time.Time   `json:"createdAt"`
	Log       []*LogEntry `json:"log"`
}

type TaskPatch struct {
	Title    *string   `json:"title,omitempty"`
	Desc     *string   `json:"desc,omitempty"`
	Project  *string   `json:"project,omitempty"`
	Priority *Priority `json:"priority,omitempty"`
	Order    *float64  `json:"order,omitempty"`
}

type Author string

const (
	AuthorUser   Author = "USER"
	AuthorClaude Author = "CLAUDE"
)

var AllAuthor = []Author{
	AuthorUser,
	AuthorClaude,
}

func (e Author) IsValid() bool {
	switch e {
	case AuthorUser, AuthorClaude:
		return true
	}
	return false
}

func (e Author) String() string {
	return string(e)
}

func (e *Author) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Author(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Author", str)
	}
	return nil
}

func (e Author) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Author) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Author) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Column string

const (
	ColumnTodo    Column = "TODO"
	ColumnDoing   Column = "DOING"
	ColumnVerify  Column = "VERIFY"
	ColumnDone    Column = "DONE"
	ColumnBlocked Column = "BLOCKED"
)

var AllColumn = []Column{
	ColumnTodo,
	ColumnDoing,
	ColumnVerify,
	ColumnDone,
	ColumnBlocked,
}

func (e Column) IsValid() bool {
	switch e {
	case ColumnTodo, ColumnDoing, ColumnVerify, ColumnDone, ColumnBlocked:
		return true
	}
	return false
}

func (e Column) String() string {
	return string(e)
}

func (e *Column) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Column(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Column", str)
	}
	return nil
}

func (e Column) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Column) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Column) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Priority string

const (
	PriorityHigh   Priority = "HIGH"
	PriorityNormal Priority = "NORMAL"
	PriorityLow    Priority = "LOW"
)

var AllPriority = []Priority{
	PriorityHigh,
	PriorityNormal,
	PriorityLow,
}

func (e Priority) IsValid() bool {
	switch e {
	case PriorityHigh, PriorityNormal, PriorityLow:
		return true
	}
	return false
}

func (e Priority) String() string {
	return string(e)
}

func (e *Priority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Priority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Priority", str)
	}
	return nil
}

func (e Priority) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Priority) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Priority) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
